/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChapterReader: typeof import('./src/components/ChapterReader.vue')['default']
    DownloadMangaChaptersDialog: typeof import('./src/components/DownloadMangaChaptersDialog.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    MangaList: typeof import('./src/components/MangaList.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
