name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        working-directory: ./src-tauri
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./src-tauri
        run: cargo test --verbose
